/// Level configurations for the game
/// 
/// Auto-generated by GameFactory.
/// Contains all 10 level configurations with difficulty curve.

class LevelConfig {
  final int levelNumber;
  final String name;
  final bool isFree;
  final String unlockRequirement;
  final double difficulty;
  final int? timeLimitSeconds;
  final int targetScore;
  final int obstacleCount;
  final double obstacleSpeed;
  final int collectibleCount;
  final int collectibleValue;
  final String backgroundTheme;

  const LevelConfig({
    required this.levelNumber,
    required this.name,
    required this.isFree,
    required this.unlockRequirement,
    required this.difficulty,
    this.timeLimitSeconds,
    required this.targetScore,
    required this.obstacleCount,
    required this.obstacleSpeed,
    required this.collectibleCount,
    required this.collectibleValue,
    required this.backgroundTheme,
  });
}

class LevelConfigs {
  LevelConfigs._();

  static const List<LevelConfig> levels = [
    LevelConfig(
      levelNumber: 1,
      name: 'Beginner's Leap',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.1,
      timeLimitSeconds: 60,
      targetScore: 100,
      obstacleCount: 5,
      obstacleSpeed: 0,
      collectibleCount: 10,
      collectibleValue: 10,
      backgroundTheme: 'grassy_meadow',
    ),
    LevelConfig(
      levelNumber: 2,
      name: 'Jumping Hurdles',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.2,
      timeLimitSeconds: 90,
      targetScore: 200,
      obstacleCount: 8,
      obstacleSpeed: 2,
      collectibleCount: 15,
      collectibleValue: 20,
      backgroundTheme: 'grassy_meadow',
    ),
    LevelConfig(
      levelNumber: 3,
      name: 'Tricky Terrain',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.3,
      timeLimitSeconds: 120,
      targetScore: 300,
      obstacleCount: 10,
      obstacleSpeed: 3,
      collectibleCount: 20,
      collectibleValue: 30,
      backgroundTheme: 'rocky_cliffs',
    ),
    LevelConfig(
      levelNumber: 4,
      name: 'Treacherous Peaks',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.4,
      timeLimitSeconds: 150,
      targetScore: 500,
      obstacleCount: 15,
      obstacleSpeed: 4,
      collectibleCount: 25,
      collectibleValue: 40,
      backgroundTheme: 'rocky_cliffs',
    ),
    LevelConfig(
      levelNumber: 5,
      name: 'Dizzying Descent',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.5,
      timeLimitSeconds: 180,
      targetScore: 750,
      obstacleCount: 20,
      obstacleSpeed: 5,
      collectibleCount: 30,
      collectibleValue: 50,
      backgroundTheme: 'rocky_cliffs',
    ),
    LevelConfig(
      levelNumber: 6,
      name: 'Perilous Passage',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.6,
      timeLimitSeconds: 210,
      targetScore: 1000,
      obstacleCount: 25,
      obstacleSpeed: 6,
      collectibleCount: 35,
      collectibleValue: 60,
      backgroundTheme: 'icy_tundra',
    ),
    LevelConfig(
      levelNumber: 7,
      name: 'Frozen Freefall',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.7,
      timeLimitSeconds: 240,
      targetScore: 1250,
      obstacleCount: 30,
      obstacleSpeed: 7,
      collectibleCount: 40,
      collectibleValue: 70,
      backgroundTheme: 'icy_tundra',
    ),
    LevelConfig(
      levelNumber: 8,
      name: 'Chilling Challenge',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.8,
      timeLimitSeconds: 270,
      targetScore: 1500,
      obstacleCount: 35,
      obstacleSpeed: 8,
      collectibleCount: 45,
      collectibleValue: 80,
      backgroundTheme: 'icy_tundra',
    ),
    LevelConfig(
      levelNumber: 9,
      name: 'Frigid Finale',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.9,
      timeLimitSeconds: 300,
      targetScore: 2000,
      obstacleCount: 40,
      obstacleSpeed: 9,
      collectibleCount: 50,
      collectibleValue: 90,
      backgroundTheme: 'icy_tundra',
    ),
    LevelConfig(
      levelNumber: 10,
      name: 'Treacherous Traverse',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 1.0,
      timeLimitSeconds: null,
      targetScore: 3000,
      obstacleCount: 45,
      obstacleSpeed: 10,
      collectibleCount: 55,
      collectibleValue: 100,
      backgroundTheme: 'icy_tundra',
    ),
  ];

  static LevelConfig getLevel(int level) {
    if (level < 1 || level > levels.length) {
      return levels.first;
    }
    return levels[level - 1];
  }

  static bool isLevelFree(int level) {
    if (level < 1 || level > levels.length) return false;
    return levels[level - 1].isFree;
  }

  static int get totalLevels => levels.length;
  static int get freeLevels => levels.where((l) => l.isFree).length;
}
